In [1]:
import torch
import torch.nn as nn
from utilities import lag_matrix
from NARX import NARX
from ANARX import ANARX
import matplotlib.pyplot as plt

In [2]:
nana = ANARX(2, [2], n_hidden=5, layersize=100)

In [3]:
outs = torch.arange(100, dtype=torch.float32)
in1 = torch.arange(100, dtype=torch.float32)
in2 = torch.arange(100, dtype=torch.float32)

in1_lagged = lag_matrix(in1, 4, 4)
in2_lagged = lag_matrix(in2, 1, 4)
out_lagged = lag_matrix(outs, 3, 4)
y_hat = torch.zeros_like(outs)
for i in range(len(y_hat)):
    y_hat[i] = nana(out_lagged[i], [in1_lagged[i], in2_lagged[i]])

plt.plot(nana.predict([in1, in2]).detach().numpy())
plt.plot(y_hat.detach().numpy())
plt.show()


TypeError: lag_matrix() takes 2 positional arguments but 3 were given

In [13]:
ana = ANARX(2, [4,2])
outs = torch.arange(4, dtype=torch.float32)
in1 = torch.arange(4, dtype=torch.float32)
in2 = torch.arange(4, dtype=torch.float32)
in1_lagged = lag_matrix(in1, 4)
in2_lagged = lag_matrix(in2, 2)
out_lagged = lag_matrix(outs, 2)
out_lagged[1,:]

# print(ana.prepare_inputs(out_lagged[2:4], [in1_lagged[2:4], in2_lagged[2:4]]))
# print(out_lagged[2:4, 1])




tensor([0., 0.])

In [26]:
a = torch.Tensor(2,2)
b = torch.Tensor(2,2)
print(a)
print(b)

tensor([[1.4013e-45, 0.0000e+00],
        [1.2711e+20, 4.5916e-41]])
tensor([[1.0000e+00, 0.0000e+00],
        [1.2711e+20, 4.5916e-41]])


In [31]:
torch.cat([b[:,1].unsqueeze(dim=0), a[:,1].unsqueeze(dim=0)], dim=0)

tensor([[0.0000e+00, 4.5916e-41],
        [0.0000e+00, 4.5916e-41]])